name: "Set Labels"
description: ""
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  labels:
    description: ""
    required: true
  github_token:
    description: ''
    required: false
    default: ${{ github.token }}
